service: management-catalogues-fridges

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512MB
  timeout: 10
  role:
    Fn::ImportValue: management-${opt:stage,'dev'}-IamRoleLambdaExecution
  apiGateway:
    restApiId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RestApiId
    restApiRootResourceId:
      Fn::ImportValue: management-${opt:stage,'dev'}-RootResourceId
# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    includeModules: 
       packagePath: '../../package.json' # enable auto-packing of external modules
plugins:
  - serverless-offline #adding the plugin to be able to run offline emulation
  - serverless-webpack   
package:
  include:
  - ../../../node_modules
functions:
  fridge-create:
    handler: FridgeHandler.create
    events:
      - http:
          path: fridge/
          method: post
          cors: true  
  fridge-getOne:
    handler: FridgeHandler.getOne
    events:
      - http:
          path: fridge/{id} 
          method: get
          cors: true     
  fridgemodel-Update:
    handler: FridgeHandler.update        
    events:
      - http:
          path: fridge/{id} 
          method: put
          cors: true 
  fridge-bysubsidiary:
    handler: FridgeHandler.bysubsidiary
    events:
      - http:
          path: fridge/by_subsidiary/{id} 
          method: get
          cors: true 
          request:
            template:
              application/json: '{  "attribute" : "$input.params(''attribute'')"  }'
        